/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AddExpenseImport } from './routes/add-expense'
import { Route as ExpenseIdImport } from './routes/expense.$id'
import { Route as EditExpenseIdImport } from './routes/edit-expense.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AddExpenseRoute = AddExpenseImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ExpenseIdRoute = ExpenseIdImport.update({
  id: '/expense/$id',
  path: '/expense/$id',
  getParentRoute: () => rootRoute,
} as any)

const EditExpenseIdRoute = EditExpenseIdImport.update({
  id: '/edit-expense/$id',
  path: '/edit-expense/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/add-expense': {
      id: '/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AddExpenseImport
      parentRoute: typeof rootRoute
    }
    '/edit-expense/$id': {
      id: '/edit-expense/$id'
      path: '/edit-expense/$id'
      fullPath: '/edit-expense/$id'
      preLoaderRoute: typeof EditExpenseIdImport
      parentRoute: typeof rootRoute
    }
    '/expense/$id': {
      id: '/expense/$id'
      path: '/expense/$id'
      fullPath: '/expense/$id'
      preLoaderRoute: typeof ExpenseIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/add-expense': typeof AddExpenseRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/expense/$id': typeof ExpenseIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/add-expense': typeof AddExpenseRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/expense/$id': typeof ExpenseIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/add-expense': typeof AddExpenseRoute
  '/edit-expense/$id': typeof EditExpenseIdRoute
  '/expense/$id': typeof ExpenseIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-expense' | '/edit-expense/$id' | '/expense/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-expense' | '/edit-expense/$id' | '/expense/$id'
  id: '__root__' | '/' | '/add-expense' | '/edit-expense/$id' | '/expense/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AddExpenseRoute: typeof AddExpenseRoute
  EditExpenseIdRoute: typeof EditExpenseIdRoute
  ExpenseIdRoute: typeof ExpenseIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AddExpenseRoute: AddExpenseRoute,
  EditExpenseIdRoute: EditExpenseIdRoute,
  ExpenseIdRoute: ExpenseIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/add-expense",
        "/edit-expense/$id",
        "/expense/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/add-expense": {
      "filePath": "add-expense.tsx"
    },
    "/edit-expense/$id": {
      "filePath": "edit-expense.$id.tsx"
    },
    "/expense/$id": {
      "filePath": "expense.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
